[versions]
kotlin = "2.1.21"
springboot = "3.5.3"
spring-dependency-management = "1.1.7"



[libraries]
jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-spring = { group = "org.jetbrains.kotlin.plugin.spring", name = "org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
springboot = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "springboot" }
spring-dependency-management = { group = "io.spring.gradle", name = "dependency-management-plugin", version.ref = "spring-dependency-management" }


[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
