[versions]
kotlin = "2.3.0"
springboot = "3.5.9"
spring-dependency-management = "1.1.7"
dokka = "2.1.0"
maven-publish = "0.35.0"

[libraries]



# gradlePlugin(buildSrc use)
#kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-jvm-gradlePlugin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-spring-gradlePlugin = {module="org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref="kotlin"}
#kotlin-jpa-gradlePlugin = {module="org.jetbrains.kotlin.plugin.jpa:org.jetbrains.kotlin.plugin.jpa.gradle.plugin", version.ref="kotlin"}
dokka-gradlePlugin = {module="org.jetbrains.dokka:dokka-gradle-plugin", version.ref="dokka"}
springboot-gradlePlugin = {module="org.springframework.boot:spring-boot-gradle-plugin", version.ref="springboot"}
spring-dependency-management-gradlePlugin = {module="io.spring.gradle:dependency-management-plugin", version.ref="spring-dependency-management"}
maven-publish-gradlePlugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }

[plugins]